CREATE ROLE ANALYST;
CREATE SCHEMA reports AUTHORIZATION ANALYST;
GRANT pg_read_all_data TO ANALYST;

CREATE ROLE READ_PUBLIC_ORDER;
GRANT SELECT ON northwind_with_security.public.orders, northwind_with_security.public.orderdetails TO READ_PUBLIC_ORDER;

CREATE ROLE READ_REPORTS;
GRANT SELECT ON ALL TABLES IN SCHEMA reports TO READ_REPORTS;
