-- From postgres
ALTER DEFAULT PRIVILEGES IN SCHEMA public FOR ROLE postgres GRANT ALL PRIVILEGES ON TABLES TO northwind_admin;
ALTER DEFAULT PRIVILEGES IN SCHEMA reports FOR ROLE postgres GRANT ALL PRIVILEGES ON TABLES TO northwind_admin;

-- From administrator
ALTER DEFAULT PRIVILEGES IN SCHEMA public FOR USER administrator GRANT ALL PRIVILEGES ON TABLES TO northwind_admin;
ALTER DEFAULT PRIVILEGES IN SCHEMA reports FOR USER administrator GRANT ALL PRIVILEGES ON TABLES TO northwind_admin;

ALTER DEFAULT PRIVILEGES IN SCHEMA public FOR USER administrator GRANT ALL PRIVILEGES ON TABLES TO public_owner;

ALTER DEFAULT PRIVILEGES IN SCHEMA reports FOR USER administrator GRANT ALL PRIVILEGES ON TABLES TO reports_owner;

ALTER DEFAULT PRIVILEGES IN SCHEMA public FOR USER administrator GRANT SELECT ON TABLES TO public_read;

ALTER DEFAULT PRIVILEGES IN SCHEMA reports FOR USER administrator GRANT SELECT ON TABLES TO reports_read;

-- From public_owner
ALTER DEFAULT PRIVILEGES IN SCHEMA public FOR ROLE public_owner GRANT ALL PRIVILEGES ON TABLES TO northwind_admin;

ALTER DEFAULT PRIVILEGES IN SCHEMA public FOR ROLE public_owner GRANT SELECT ON TABLES TO public_read;

-- From reports_owner
ALTER DEFAULT PRIVILEGES IN SCHEMA reports FOR ROLE reports_owner GRANT ALL PRIVILEGES ON TABLES TO northwind_admin;

ALTER DEFAULT PRIVILEGES IN SCHEMA reports FOR ROLE reports_owner GRANT SELECT ON TABLES TO reports_read;

-- From analyst
ALTER DEFAULT PRIVILEGES IN SCHEMA reports FOR USER analyst GRANT ALL PRIVILEGES ON TABLES TO northwind_admin;

ALTER DEFAULT PRIVILEGES IN SCHEMA reports FOR USER analyst GRANT SELECT ON TABLES TO reports_read;

-- From northwind_admin
ALTER DEFAULT PRIVILEGES IN SCHEMA public FOR USER northwind_admin GRANT ALL PRIVILEGES ON TABLES TO public_owner;

ALTER DEFAULT PRIVILEGES IN SCHEMA reports FOR USER northwind_admin GRANT ALL PRIVILEGES ON TABLES TO reports_owner;

ALTER DEFAULT PRIVILEGES IN SCHEMA public FOR USER northwind_admin GRANT SELECT ON TABLES TO public_read;
ALTER DEFAULT PRIVILEGES IN SCHEMA reports FOR USER northwind_admin GRANT SELECT ON TABLES TO reports_read;
